src/Entity/Chambre.php
<?php

namespace App\Entity;

use App\Repository\ChambreRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChambreRepository::class)
 */
class Chambre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description_courte;

    /**
     * @ORM\Column(type="text")
     */
    private $description_longue;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $photo;

    

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescriptionCourte(): ?string
    {
        return $this->description_courte;
    }

    public function setDescriptionCourte(string $description_courte): self
    {
        $this->description_courte = $description_courte;

        return $this;
    }

    public function getDescriptionLongue(): ?string
    {
        return $this->description_longue;
    }

    public function setDescriptionLongue(string $description_longue): self
    {
        $this->description_longue = $description_longue;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Controller/ChambreController.php
<?php

namespace App\Controller;

use App\Entity\Chambre;
use App\Entity\Commande;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ChambreController extends AbstractController
{
    /**
     * @Route("/chambre", name="chambre_show", methods={"GET"})
     */

   public function show(EntityManagerInterface $entityManager): Response
   {


       return $this->render('chambre/show_chambre.html.twig', [
           'chambres' => $entityManager->getRepository(Chambre::class)->findAll()
       ]);
   }


   


}

templates/chambre/show_chambre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voir les chambres{% endblock %}

{% block body %}

{% if app.flashes %}
        <div class="row">
            <div class="col-9 mx-auto mb-5">
                {% include 'include/_flashes.html.twig' %}
            </div>
        </div>
    {% endif %}

    {% for chambre in chambres %}
        <div>
    
          
                <img src="{{ asset('uploads/' ~ chambre.photo) }}" class="card-img-top" alt="une photo" style="object-fit: contain;" width="230" height="200">
                <div class="card-body">
                    <h5 class="card-title title">{{ chambre.titre }}</h5>
                    <p class="card-text description">{{ chambre.descriptionCourte  }}</p>
                    <p class="card-text col-9 mx-auto mb-5 ">{{ chambre.descriptionLongue  }} </p>
                </div>
        </div>

     
    {% endfor %}

{% endblock %}

templates/chambre/show_slider.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voir les chambres{% endblock %}

{% block body %}
            <h1 class="text-center"  >Bienvenue</h1>
{% if app.flashes %}
        <div class="row">
            <div class="col-9 mx-auto mb-5">
                {% include 'include/_flashes.html.twig' %}
            </div>
        </div>
    {% endif %}

    {% for slider in sliders %}
        <div class="">
    
          
                <img src="{{ asset('uploads/' ~ slider.photo) }}" class="card-img-top" alt="une photo" style="object-fit: contain;" width="230" height="200">
                <hr>
        </div>

     
    {% endfor %}

{% endblock %}